"""Builds the installable app: a shell that fetches a fresh brief every morning.

The single-file page in `out/` embeds one episode and never changes. This
builds the other thing you want - a small site you install to a home screen
once, which then picks up each new episode on its own and keeps the last one
playable when you drive through a tunnel.
"""

from __future__ import annotations

import json
import shutil
from datetime import date
from pathlib import Path

from . import feed as feed_mod
from . import icons, render
from .model import Watchlist
from .script import Episode

APP_NAME = "Startup Brief Radio"
SHORT_NAME = "Brief Radio"
THEME = "#0B1F24"
STYLE_END = "</style>"


def _manifest() -> str:
    return json.dumps({
        "name": APP_NAME,
        "short_name": SHORT_NAME,
        "description": "A daily, listenable brief on funded and fast-moving startups.",
        "start_url": "./",
        "scope": "./",
        "display": "standalone",
        "orientation": "portrait",
        "background_color": THEME,
        "theme_color": THEME,
        "categories": ["news", "business", "education"],
        "icons": [
            {"src": "icon-192.png", "sizes": "192x192", "type": "image/png",
             "purpose": "any maskable"},
            {"src": "icon-512.png", "sizes": "512x512", "type": "image/png",
             "purpose": "any maskable"},
        ],
    }, indent=2)


def _service_worker(build_id: str) -> str:
    shell = ["./", "./index.html", "./manifest.webmanifest",
             "./icon-192.png", "./icon-512.png", "./apple-touch-icon.png"]
    return f"""// Generated by briefing.site — build {build_id}
const SHELL = "brief-shell-{build_id}";
const DATA = "brief-data";
const FILES = {json.dumps(shell)};

self.addEventListener("install", (event) => {{
  event.waitUntil(caches.open(SHELL).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
}});

self.addEventListener("activate", (event) => {{
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k !== SHELL && k !== DATA).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
}});

self.addEventListener("fetch", (event) => {{
  const request = event.request;
  if (request.method !== "GET") return;
  const isData = new URL(request.url).pathname.includes("/data/");

  if (isData) {{
    // Newest brief when there is signal, this morning's when there is not.
    event.respondWith(
      fetch(request)
        .then((response) => {{
          const copy = response.clone();
          caches.open(DATA).then((c) => c.put(request, copy));
          return response;
        }})
        .catch(() => caches.match(request))
    );
    return;
  }}
  event.respondWith(caches.match(request).then((hit) => hit || fetch(request)));
}});
"""


def _document(fragment: str, build_id: str) -> str:
    if STYLE_END not in fragment:
        raise ValueError("template has no <style> block to split on")
    cut = fragment.index(STYLE_END) + len(STYLE_END)
    head, body = fragment[:cut], fragment[cut:]
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="description" content="A daily, listenable brief on funded and fast-moving startups.">
<meta name="theme-color" content="{THEME}">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="{SHORT_NAME}">
<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="favicon-32.png">
<meta name="build" content="{build_id}">
{head}
</head>
<body>
{body}
</body>
</html>
"""


def build(episodes: list[tuple[Episode, Watchlist]], out_dir: Path, template: Path,
          source_dir: Path | None = None, base_url: str = "") -> dict[str, Path]:
    """Write the whole site. `episodes` is newest-first; the first one ships embedded."""
    if not episodes:
        raise ValueError("no episodes to publish")
    out_dir.mkdir(parents=True, exist_ok=True)
    data_dir = out_dir / "data"
    data_dir.mkdir(exist_ok=True)

    latest_episode, latest_watchlist = episodes[0]
    build_id = latest_episode.date

    index = []
    for episode, watchlist in episodes:
        payload = render.payload(episode, watchlist)
        (data_dir / f"{episode.date}.json").write_text(
            json.dumps(payload, ensure_ascii=False), encoding="utf-8")
        index.append({
            "date": episode.date,
            "title": episode.title,
            "seconds": episode.seconds,
            "companies": [s.heading for s in episode.segments if s.kind == "company"],
        })
    (data_dir / "latest.json").write_text(
        (data_dir / f"{latest_episode.date}.json").read_text(encoding="utf-8"),
        encoding="utf-8")
    (data_dir / "index.json").write_text(
        json.dumps(index, ensure_ascii=False), encoding="utf-8")

    fragment = render.html(latest_episode, latest_watchlist, template)
    (out_dir / "index.html").write_text(_document(fragment, build_id), encoding="utf-8")
    (out_dir / "manifest.webmanifest").write_text(_manifest(), encoding="utf-8")
    (out_dir / "sw.js").write_text(_service_worker(build_id), encoding="utf-8")
    icons.write_set(out_dir)
    (out_dir / ".nojekyll").write_text("", encoding="utf-8")

    audio_entries = []
    if source_dir:
        for mp3 in sorted(source_dir.glob("brief-*.mp3")):
            shutil.copy2(mp3, out_dir / mp3.name)
            stamp = mp3.stem.replace("brief-", "")
            match = next((e for e in index if e["date"] == stamp), None)
            if match:
                audio_entries.append({**match, "audio": mp3.name,
                                      "bytes": mp3.stat().st_size,
                                      "summary": ", ".join(match["companies"])})
    if audio_entries and base_url:
        feed_mod.write(out_dir / "feed.xml", audio_entries, base_url, title=APP_NAME)

    return {
        "index": out_dir / "index.html",
        "manifest": out_dir / "manifest.webmanifest",
        "service_worker": out_dir / "sw.js",
        "data": data_dir,
    }
