"""Optional audio rendering.

Nothing here is required to *read* the brief — the HTML player speaks it with
the voice already in your phone. This module exists for the version you want in
a podcast app: real audio files, generated by whatever engine you have.

Backends are tried in order of quality. Install one:
    pip install edge-tts        # free, network, very natural
    brew install piper          # offline
    (macOS `say` and `espeak-ng` are used automatically if present)
"""

from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .script import Episode


@dataclass(frozen=True)
class Backend:
    name: str
    executable: str

    def command(self, text: str, out_path: Path, voice: str) -> list[str]:
        if self.name == "edge-tts":
            return [self.executable, "--voice", voice or "en-US-AndrewMultilingualNeural",
                    "--text", text, "--write-media", str(out_path)]
        if self.name == "piper":
            return [self.executable, "--model", voice or "en_US-lessac-medium",
                    "--output_file", str(out_path)]
        if self.name == "say":
            return [self.executable, "-v", voice or "Samantha", "-o", str(out_path), text]
        if self.name == "espeak-ng":
            return [self.executable, "-v", voice or "en-us", "-w", str(out_path), text]
        raise ValueError(self.name)

    @property
    def wants_stdin(self) -> bool:
        return self.name == "piper"

    @property
    def suffix(self) -> str:
        return {"edge-tts": ".mp3", "piper": ".wav", "say": ".aiff", "espeak-ng": ".wav"}[self.name]


CANDIDATES = ("edge-tts", "piper", "say", "espeak-ng")


def detect() -> Backend | None:
    for name in CANDIDATES:
        found = shutil.which(name)
        if found:
            return Backend(name=name, executable=found)
    return None


def synthesize(episode: Episode, out_dir: Path, voice: str = "",
               backend: Backend | None = None) -> list[Path]:
    """Render one audio file per segment. Returns the files, in play order."""
    backend = backend or detect()
    if backend is None:
        raise RuntimeError(
            "No text-to-speech engine found. Install one with `pip install edge-tts`, "
            "or just use the HTML player, which needs nothing."
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for position, segment in enumerate(episode.segments):
        target = out_dir / f"{position:02d}-{segment.id}{backend.suffix}"
        command = backend.command(segment.speak, target, voice)
        stdin = segment.speak.encode() if backend.wants_stdin else None
        subprocess.run(command, input=stdin, check=True, capture_output=True)
        written.append(target)
    return written


def stitch(parts: list[Path], out_file: Path) -> Path | None:
    """Join segments into one episode file. Needs ffmpeg; returns None without it."""
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg or not parts:
        return None
    manifest = out_file.with_suffix(".txt")
    manifest.write_text(
        "\n".join(f"file '{p.resolve()}'" for p in parts) + "\n", encoding="utf-8"
    )
    subprocess.run(
        [ffmpeg, "-y", "-f", "concat", "-safe", "0", "-i", str(manifest),
         "-c:a", "libmp3lame", "-b:a", "96k", str(out_file)],
        check=True, capture_output=True,
    )
    manifest.unlink(missing_ok=True)
    return out_file


def playlist(parts: list[Path], out_file: Path) -> Path:
    """An m3u fallback so a car stereo can play the segments in order."""
    lines = ["#EXTM3U"] + [os.path.relpath(p, out_file.parent) for p in parts]
    out_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_file
